spring:
  application:
    name: Spring-Security-App
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=your_database;encrypt=true;trustServerCertificate=true
    username: your_username
    password: your_password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update  # Use 'validate' in production
    show-sql: true

